### ISSUE TITLE
Issues with Makefile/mix deps.compile

### ISSUE THREAD

**Issue by imayhaveborkedit** [joshnuss/elixir-ffi#2]
Aside from the outdated erts path version and needing to add the `-fPIC` flag, mix seems to have problems compiling this lib.  This may have worked fine in the past but not anymore.  Compiling as a dependency fails but strangely, compiling the app itself works fine (`mix compile` in the deps/ffi folder).  

Reproduction is trivial:

1. Make a new project with mix
2. Add the lib in deps
3. Fix the erts path version and add `-fPIC` if needed in the Makefile
4. `mix deps.get`
5. `mix deps.compile`

Mix will proceed to complain about not finding a Makefile or targets and fail.  Adding an empty Makefile to your dir changes the error message to just not finding targets, but adding `compile: "echo \`pwd\`"` to the dep entry makes it print the correct dir.  Presumably this means that for some reason its looking in the project dir for a Makefile instead of the ffi dep folder.  I don't know much about how this all works and I don't have much experience with Elixir and mix but something is clearly wrong.

**Comment by imayhaveborkedit** [comment]
Note: This is with `erlang-dev` and friends installed.  Reinstalling `esl-erlang` (and having `erlang-dev` and friends removed) changes error.  It seems it finds the Makefile properly since the output is:
```
$ mix deps.compile ffi
gcc -c -o c_src/ffi_nif.o c_src/ffi_nif.c -fPIC -I/erts-8.1/include
c_src/ffi_nif.c:3:21: fatal error: erl_nif.h: No such file or directory
compilation terminated.
make: *** [c_src/ffi_nif.o] Error 1
```
even though these exist
```
$ locate rl_nif.h
/usr/lib/erlang/erts-8.1/include/erl_nif.h
/usr/lib/erlang/usr/include/erl_nif.h
```

**Comment by joshnuss** [comment]
@imayhaveborkedit seems the way the Makefile currently determines the location of erl_nif.h could be better

on my machine REBAR_PLT_DIR point to `~/erlangs/`,
on your machine it should point to `/usr/lib/erlang`

First thing, can you check if REBAR_PLT_DIR is defined? e.g. `echo $REBAR_PLT_DIR`

Secondly, the erts version (8.1 in your case, 8.0 in my case) should be determined dynamically by the Makefile. I'll need to figure out how to do that.

For now, can you try setting ERTS_INCLUDE_PATH and let me know what happens? e.g. `ERTS_INCLUDE_PATH=/usr/lib/erlands/erts-8.1/include make`

**Comment by imayhaveborkedit** [comment]
I did manage to get it working by manually setting the erts include path in the Makefile, and `$REBAR_PLT_DIR` is indeed not defined.

**Comment by imayhaveborkedit** [comment]
I was looking at how to find the erts version and I found this:
```
$ erl -noshell -eval 'io:fwrite("~s\n", [erlang:system_info(system_version)]).' -s erlang halt
Erlang/OTP 19 [erts-8.1] [source-e7be63d] [64-bit] [smp:8:8] [async-threads:10] [hipe] [kernel-poll:false]
```
Running and parsing that seems a bit sketchy but I guess it could work.
